M48
; DRILL file {KiCad 9.0.1} date 2025-06-24T23:42:47-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-24T23:42:47-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C1.000
%
G90
G05
T1
X151.5Y-97.0
X151.5Y-109.5
T2
X152.0Y-99.0
X152.0Y-102.0
X152.0Y-104.5
X152.0Y-107.5
M30
